version: '3.8'

services:
  fudo_challenge:
    container_name: fudo_challenge 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - DATABASE_FILE_PATH=db/fudochallenge.sqlite3
      - SECRET_KEY=7ad2ebfc87a1c7756b2ea72c107c1001c65a420749f506e8ef38321057342f88
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - .:/app
    command: bundle exec puma -b 'tcp://0.0.0.0:${PORT:-5000}'
  swagger:
    container_name: fudo_challenge_swagger
    image: swaggerapi/swagger-ui
    ports:
      - 8000:8000
    environment:
      SWAGGER_JSON: /swagger/openapi.yaml
    volumes:
      - ./public:/swagger
    depends_on:
      - fudo_challenge 
    network_mode: host
